version: '3'
services:
  search-service:
    image: search-service:latest
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on: 
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment: 
      - discovery.type=single-node
    container_name: elasticsearch
    ports: ['9200:9200']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 10s
      retries: 5
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']